import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Uploadphoto from '../component/Uploadphoto'
import UpMulti from '../component/UpMulti'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Upload Photo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UpMulti/>
    </div>
  )
}
